### ISSUE TITLE
Request: Search in a single response

### ISSUE THREAD

**Issue by PeterVdBoogaard** [roryc89/network-filter#1]
Hi Rory,

First let me thank you for sharing this extension.
It works but i was wondering if you could change it so you're able search in a single request response.

The way it is now (in my SPA case, during development) it's too slow because i have too many request and response data in the network tab. Some of them with a sh*tload of un-minified js etc.

I was thinking a button for each response for deleting all but that response.

Regards
  Peter

**Comment by roryc89** [comment]
Thanks Peter. Due to lack of time, I'm afraid I don't think I'll be making many commits to this.

 If it's too slow, try hitting the get network button quickly after you open devtools so there isnt too many too much stored traffic and uncheck "highlight search results" first.

Also, if you know the req/res you want, I would have thought you could copy as HAR that req/res and then paste it into a text editor and search for the text you want. But maybe I've misunderstood?
